server:
  port: 8082


spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave
      master:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/tzn?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/tzn?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
    props:
      sql:
        show: true
    sharding:
      binding-tables: product
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave
          load-balance-algorithm-type: round_robin
      tables:
        product:
          actual-data-nodes: ds0.product$->{0..1}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: product$->{id % 2}
              sharding-column: id
  thymeleaf:
        cache: false
        mode: HTML
